http:
  host: "localhost"
  port: 8080

email:
  host: "smtp.gmail.com" #стандартный хост, если используете google
  port: 587              #стандартный порт для smtp
  from:                  #email адрес, с которого будут отправлены уведомления

log_mode: "dev"          #dev || prod